# applicationsets/it-springboot-appset.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: it-springboot-services
  namespace: argocd
spec:
  generators:
    - git:                                      # ← directly here, no matrix wrapper
        repoURL: https://github.com/rxummadi/gitops-umbrella-charts.git
        revision: HEAD
        files:
          - path: "service-registry/it-springboot-services.yaml"


  template:
    metadata:
      name: "{{ service_name }}"
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: default
      sources:
        # Source 1: The umbrella chart from GitHub Pages
        - repoURL: https://rxummadi.github.io/helm-charts/
          chart: springboot-bundle
          targetRevision: "1.0.0"               # ← single version pin for ALL services
          helm:
            releaseName: "{{ service_name }}"
            valueFiles:
              - $values/values/values.yaml
  
        - repoURL: https://github.com/rxummadi/web-service.git
          targetRevision: HEAD
          ref: values               

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ env }}"

      syncPolicy:
        automated:                               # AUTO SYNC for IT ✅
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true